server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carsystem?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
